absolute_urls: false

home:
  alias: '/home'

pages:
  theme: bootstrapndlc
  markdown_extra: true
  process:
    markdown: true
    twig: true

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: false
  log: false

debugger:
  enabled: false
  twig: false
  shutdown:
    close_connection: true